# Generated by Django 5.2 on 2025-05-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_slot'),
        ('doctors', '0003_alter_doctors_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('slot', 'doctor')},
        ),
    ]
