# Generated by Django 5.2 on 2025-04-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('doctor', 'پزشک'), ('patient', 'بیمار'), ('admin', 'مدیر')], default='patient', max_length=10, verbose_name='نوع کاربر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('full_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='نام کامل')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
