# Generated by Django 5.2 on 2025-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(max_length=400, verbose_name='نام کامل'),
        ),
    ]
