# Generated by Django 5.2 on 2025-04-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': ' کاربران'},
        ),
    ]
