# Generated by Django 5.2 on 2025-04-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='specialits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/%y-%M/')),
                ('available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='dr_profile', to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.specialits')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='DoctorWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یکشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه شنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنج شنبه')], max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('visit_duration', models.PositiveBigIntegerField(help_text='مثلا 20 دقیقه')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabls', to='doctors.doctors')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': ' برنامه ها',
            },
        ),
    ]
