# Generated by Django 5.2 on 2025-04-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/%y-%M/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='speciality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.specialits'),
        ),
    ]
